name: mms
description: "MMS project "

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android
  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type
  flutter_slidable: ^3.1.0
  introduction_screen: ^3.1.14
  android_power_manager: ^1.0.0
  group_button: ^5.3.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0
  http: ^1.2.1
  bottom_navy_bar:
  flutter_keyboard_visibility: ^6.0.0
  shared_preferences: ^2.2.3
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  pinput: ^4.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
  logger: ^2.2.0
  dropdown_button2: ^2.3.9
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.1
  geolocator: ^11.0.0
  intl: ^0.18.1
  collection: ^1.18.0
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_local_notifications: ^17.1.1
  package_info_plus: ^8.0.0
  flutter_async_autocomplete: ^0.1.1
  multi_select_flutter: ^4.1.3
  percent_indicator: ^4.2.3
  hive: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  awesome_dialog: ^3.2.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: cairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: cairoSemiBold
      fonts:
        - asset: assets/fonts/cairo_semi_bold.ttf

flutter_intl:
  enabled: true
