name: mms
description: "MMS project "

publish_to: 'none'

version: 1.0.0+2.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  drawable_text: ^1.0.0

  m_cubit:
    path: ../../packages/m_cubit

  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type


  #  flutter_slidable:
  #  flutter_switch:
  #  introduction_screen: ^4.0.0
  #  android_power_manager: ^1.0.0
  group_button: ^5.3.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  http:
  #  bottom_navy_bar:
  #  flutter_keyboard_visibility: ^6.0.0
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.2
  carousel_slider: ^5.1.1
  #  flutter_rating_bar: ^4.0.1
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  logger: ^2.6.1
  dropdown_button2: ^2.3.9
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  #  geolocator: ^14.0.2
  intl: ^0.20.2
  collection: ^1.19.1
  #  path_provider:
  #  path:
  flutter_local_notifications: ^19.4.2
  package_info_plus: ^9.0.0
  #  flutter_async_autocomplete: ^0.1.1
  #  multi_select_flutter: ^4.1.3
  #  percent_indicator: ^4.2.5
  hive: ^2.2.3
  internet_connection_checker: ^3.0.1
  awesome_dialog: ^3.2.1
  #  firebase_auth: ^6.0.2
  #  google_sign_in: ^7.2.0
  hive_flutter: ^1.1.0
  #  geocoding: ^4.0.0
#  agora_rtc_engine: ^6.5.3
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  table_calendar: ^3.2.0
  crypto:
  fl_chart: ^0.68.0
  pull_to_refresh: ^2.0.0
  agora_rtc_engine: ^6.5.3
#  permission_handler:
  #  flutter_polls: ^0.1.6
  animated_tree_view: ^2.3.0

dev_dependencies:

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: cairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: cairoSemiBold
      fonts:
        - asset: assets/fonts/cairo_semi_bold.ttf

flutter_intl:
  enabled: true
